### ISSUE TITLE
Problem with the sample

### ISSUE THREAD

**Issue by placidodaniel** [svmk/swagger-i18n-extension#1]
using the example, the following error occurs:
Sample:

```
openapi: 3.0.0
info:
  version: 0.0.2
  title: Swagger example in default language
  x-title-i18n:
    eng: Title on english
  description: This text will be translated in english
  x-description-i18n:
    eng: Description on english
```
Error:
```
$ swagger-i18n-extension validate teste.json 

/usr/lib/node_modules/swagger-i18n-extension/node_modules/yargs/yargs.js:1148
      else throw err
           ^

SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadFromFile (/usr/lib/node_modules/swagger-i18n-extension/bin/swagger-i18n-extension:27:21)
    at Object.handler (/usr/lib/node_modules/swagger-i18n-extension/bin/swagger-i18n-extension:131:31)
    at Object.runCommand (/usr/lib/node_modules/swagger-i18n-extension/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/swagger-i18n-extension/node_modules/yargs/yargs.js:1063:30)
    at Object.get [as argv] (/usr/lib/node_modules/swagger-i18n-extension/node_modules/yargs/yargs.js:1004:21)
    at Object.<anonymous> (/usr/lib/node_modules/swagger-i18n-extension/bin/swagger-i18n-extension:141:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Would you help me?

**Comment by svmk** [comment]
You're parsing YAML file as json file.
Rename file `teste.json` to `teste.yaml`
